### ISSUE TITLE
Moving var to let/const breaks some browsers

### ISSUE THREAD

**Issue by adrienharnay** [bendrucker/fast-luhn#19]
Hey,

Just wanted to let you know [this commit](https://github.com/bendrucker/fast-luhn/commit/a69677924642f0cdc577e8315fc23d1cc6bb9212) breaks support for Chrome on Android 5.1 and lesser (specifically Chrome 39 and lesser). I've added the module to the list of node_modules I transpile in my project, but thought I would let you know in case you would wish to support these browsers.

Thanks for your work and have a nice evening!

**Comment by bendrucker** [comment]
Understood, this was a major release. So hopefully you noticed this as part of explicitly opting in to that version. It was intended though, thanks!

**Comment by adrienharnay** [comment]
Yes, all good and thanks again for fast-luhn!
